modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3.0"

issueTrackerURL="https://github.com/62832/MEGACells/issues"
displayURL="https://github.com/62832/MEGACells"

[[mods]]
modId="megacells"
version="${version}"
displayName="MEGA Cells"
logoFile="logo.png"
credits="s/o to Technici4n, Gimpansor, MasterYodA, PrototypeTrousers, ramidzkh, RaVen"
authors="90"
description='''
ME Greater Accumulation Cells - For when kilobytes just won't do.
'''

[[dependencies.megacells]]
    modId="ae2"
    mandatory=true
    versionRange = "[12.8.2-beta,13.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.megacells]]
    modId="appmek"
    mandatory=false
    versionRange = "(,2.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.megacells]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.megacells]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
