name: 'Release'

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate data
        run: ./gradlew downloadAssets runData --max-workers 1
      - name: Build release files
        env:
          MEGA_VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew build --max-workers 1
      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/megacells-*.jar
          tag_name: ${{ github.event.release.tag_name }}
      - name: Upload to mod repositories
        env:
          MEGA_VERSION: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}
          CF_TOKEN: ${{ secrets.CURSEFORGE_API_KEY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_API_KEY }}
        run: ./gradlew :fabric:publishUnified :forge:publishUnified --max-workers 1